/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-high": "#2a2a2a",
        "surface-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c2c6d6",
        "outline": "#8c909f",
        "outline-variant": "#424754",
        primary: "#adc6ff",
        "primary-container": "#4d8eff",
        "on-primary": "#002e6a",
        secondary: "#c6c4df",
        "secondary-container": "#47475d",
        tertiary: "#bcc7de",
        "tertiary-container": "#8691a7",
        error: "#ffb4ab",
        "error-container": "#93000a",
        background: "#131313",
        "on-background": "#e5e2e1",
        // Category colors
        "cat-tech": "#1a2744",
        "cat-tech-text": "#5b9cf6",
        "cat-legal": "#1e1a2e",
        "cat-legal-text": "#a78bfa",
        "cat-finance": "#2a1a1a",
        "cat-finance-text": "#f87171",
        "cat-healthcare": "#1a2a1a",
        "cat-healthcare-text": "#4ade80",
        "cat-mgmt": "#2a1f0a",
        "cat-mgmt-text": "#fbbf24",
        "expert-border": "#f59e0b",
        "verified-text": "#4ade80",
      },
      fontFamily: {
        sans: ["Inter", "System"],
      },
      borderRadius: {
        sm: "2px",
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
